Command line parameters are parsed usign getopt

diff --git a/git-tf b/git-tf
--- a/git-tf
+++ b/git-tf
@@ -26,7 +26,6 @@ exitCode=0
 verbose=true
 noChecks=
 debug=
-exec=
 tmpDir=/tmp/git-tf
 # main commands
 number=9999999
@@ -270,17 +269,21 @@ init() {
   mkdir -p $tmpDir
 }
 readOptions() {
-  lastOption=""
-  for o; do
-    if [ "${o:0:2}" = "--" ]; then
-      lastOption=${o:2}
-      debug "option found: $lastOption"
-      eval $lastOption=true
-    elif [ ! -z $lastOption ]; then
-      debug "option $lastOption=$o"
-      eval $lastOption=$o
-      lastOption=""
+  args=`getopt -o vCn --long verbose,debug,noChecks,number: -n git-tf -- "$@"`
+  if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 10 ; fi
+  set -- $args
+  while true ; do
+    if [ "$1" != "--" -a "$debug" ]; then
+      echo "Option found: " $1
     fi
+    case "$1" in
+      -v|--verbose) verbose=true; shift ;;
+      -d|--debug) debug=true; shift ;;
+      -C|--noChecks) noChecks=true; shift ;;
+      -n|--number) number=$2; shift 2 ;;
+      --) shift ; break ;;
+      *) echo "Internal error!" ; exit 1 ;;
+    esac
   done
 }
 main() {
